services:
  - type: web
    name: agente-ventas-ia
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false